services:
  postgres-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: trungdung
      POSTGRES_PASSWORD: trungdung2474
      POSTGRES_DB: EchoVault
    networks:
      - EchoVault-Network

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: echovault-pgadmin
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: trungdung@echovault.com
  #     PGADMIN_DEFAULT_PASSWORD: trungdung2474
  #   ports:
  #     - '5050:80'
  #   networks:
  #     - Echovault-Network
networks:
  EchoVault-Network: